#!/usr/bin/env ruby

require 'boreman'
require 'optparse'

opts = {}

OptionParser.new do |o|
  o.banner = 'Usage: boreman [start|stop|restart|status] [selector]'
end.parse!

action   = ARGV[0]
selector = ARGV[1]

Boreman.run action, selector, opts
